image:
  tag: "latest"
  pullPolicy: Always

database:
  url: ""
  existingSecret: civicgrid-database
  existingSecretKey: DATABASE_URL

replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

# Enable Prometheus scraping
serviceMonitor:
  enabled: true
  interval: 30s

# Admin token Secret created by Terraform in civicgrid-infra
admin:
  existingSecret: civicgrid-admin
  existingSecretKey: ADMIN_TOKEN
